@extends('layouts.client-store')

@section('content')
<div class="kt-container-fixed max-w-[1100px]">
    <div class="flex flex-wrap items-center justify-between gap-3 mb-7.5"><div><h1 class="text-xl font-medium text-mono">Mi cuenta Cloud</h1><p class="text-sm text-secondary-foreground mt-1">Identidad comercial, servicios contratados y facturación.</p></div><a class="kt-btn kt-btn-outline" href="{{ route('client.plans.index') }}"><i class="ki-filled ki-handcart"></i> Contratar hosting</a></div>
    <div class="grid lg:grid-cols-3 gap-5">
        <div class="kt-card lg:col-span-2"><div class="kt-card-header"><h2 class="kt-card-title">Información del cliente</h2><span class="kt-badge kt-badge-outline {{ $tenant->status === 'active' ? 'kt-badge-success' : 'kt-badge-warning' }}">{{ ucfirst($tenant->status) }}</span></div><div class="kt-card-table kt-scrollable-x-auto pb-3"><table class="kt-table align-middle text-sm"><tr><td class="text-secondary-foreground">Nombre</td><td>{{ $tenant->user?->name }}</td></tr><tr><td class="text-secondary-foreground">Correo</td><td>{{ $tenant->user?->email }}</td></tr><tr><td class="text-secondary-foreground">Empresa</td><td>{{ $tenant->name }}</td></tr><tr><td class="text-secondary-foreground">Código</td><td><span class="kt-badge kt-badge-outline">{{ $tenant->code }}</span></td></tr></table></div></div>
        <div class="grid gap-4"><div class="kt-card"><div class="kt-card-content p-5"><div class="text-sm text-secondary-foreground">Hostings</div><div class="text-3xl font-semibold text-mono mt-2">{{ $usage['hostings'] }}</div></div></div><div class="kt-card"><div class="kt-card-content p-5"><div class="text-sm text-secondary-foreground">Boletas pendientes</div><div class="text-3xl font-semibold text-mono mt-2">{{ $usage['pending_invoices'] }}</div></div></div></div>
    </div>
    <div class="kt-card mt-5"><div class="kt-card-header"><h2 class="kt-card-title">Servicios de hosting</h2><a class="kt-link" href="{{ route('client.host.show') }}">Administrar todos</a></div><div class="kt-card-table kt-scrollable-x-auto"><table class="kt-table align-middle"><thead><tr><th>Cuenta</th><th>Plan</th><th>Panel</th><th>Estado</th></tr></thead><tbody>@forelse($hostingAccounts as $account)<tr><td><a class="kt-link font-medium" href="{{ route('client.host.account', $account) }}">{{ $account->name }}</a></td><td>{{ $account->plan?->name ?? 'Sin plan' }}</td><td>{{ $account->custom_panel_domain ?: ($account->hostInstance?->panel_domain ?? 'Preparando') }}</td><td><span class="kt-badge kt-badge-outline {{ $account->status === 'active' ? 'kt-badge-success' : 'kt-badge-warning' }}">{{ ucfirst($account->status) }}</span></td></tr>@empty<tr><td colspan="4" class="py-8 text-center text-secondary-foreground">No hay hostings contratados.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
