@extends('layouts.admin')

@section('content')
<div class="flex grow rounded-b-xl bg-background border-x border-b border-input lg:mt-(--navbar-height) mx-5 lg:ms-(--sidebar-width) mb-5"><div class="flex flex-col grow kt-scrollable-y pt-7"><main class="grow"><div class="kt-container-fluid">
    <div class="flex flex-wrap items-center justify-between gap-3 mb-7.5"><div><h1 class="text-2xl font-semibold text-mono">Contrataciones</h1><p class="text-sm text-secondary-foreground mt-1">El servicio se habilita al contratar; aquí se controla la boleta por separado.</p></div><div class="flex gap-2"><a class="kt-btn {{ request('payment_status') ? 'kt-btn-outline' : 'kt-btn-primary' }}" href="{{ route('admin.orders.index') }}">Todas</a><a class="kt-btn {{ request('payment_status') === 'pending' ? 'kt-btn-primary' : 'kt-btn-outline' }}" href="{{ route('admin.orders.index', ['payment_status' => 'pending']) }}">Pagos pendientes</a></div></div>
    <div class="kt-card"><div class="kt-card-table kt-scrollable-x-auto"><table class="kt-table align-middle text-sm"><thead><tr><th>Boleta</th><th>Cliente</th><th>Plan</th><th>Total</th><th>Vence</th><th>Servicio</th><th>Pago</th><th></th></tr></thead><tbody>
    @forelse($orders as $order)<tr><td class="font-medium text-mono">{{ $order->number }}</td><td><div class="font-medium">{{ $order->tenant->name }}</div><div class="text-xs text-secondary-foreground">{{ $order->tenant->user?->email }}</div></td><td>{{ $order->plan->name }}</td><td>{{ $order->currency }} {{ number_format((float) $order->amount, 2) }}</td><td>{{ $order->payment_due_at->format('d/m/Y') }}</td><td><span class="kt-badge kt-badge-outline {{ $order->status === 'active' ? 'kt-badge-success' : '' }}">{{ ucfirst($order->status) }}</span></td><td><span class="kt-badge kt-badge-outline {{ $order->payment_status === 'paid' ? 'kt-badge-success' : 'kt-badge-warning' }}">{{ $order->payment_status === 'paid' ? 'Pagado' : 'Pendiente' }}</span></td><td class="text-right"><a class="kt-btn kt-btn-sm kt-btn-outline" href="{{ route('admin.orders.show', $order) }}">Gestionar</a></td></tr>
    @empty<tr><td colspan="8" class="py-10 text-center text-secondary-foreground">No hay contrataciones todavía.</td></tr>@endforelse
    </tbody></table></div></div><div class="mt-5">{{ $orders->links() }}</div>
</div></main>@include('layouts.partials.admin.footer')</div></div>
@endsection
