@extends('layouts.admin')

@section('content')
<div class="flex grow rounded-b-xl bg-background border-x border-b border-input lg:mt-(--navbar-height) mx-5 lg:ms-(--sidebar-width) mb-5"><div class="flex flex-col grow kt-scrollable-y pt-7"><main class="grow"><div class="kt-container-fluid max-w-[1100px]">
    <div class="flex flex-wrap items-center justify-between gap-3 mb-7.5"><div><a class="kt-link text-sm" href="{{ route('admin.orders.index') }}">Volver a contrataciones</a><h1 class="text-2xl font-semibold text-mono mt-2">{{ $order->number }}</h1></div><div class="flex gap-2"><span class="kt-badge kt-badge-outline kt-badge-success">Servicio {{ $order->status }}</span><span class="kt-badge kt-badge-outline {{ $order->payment_status === 'paid' ? 'kt-badge-success' : 'kt-badge-warning' }}">Pago {{ $order->payment_status }}</span></div></div>
    @if(session('success'))<div class="kt-alert kt-alert-success mb-5">{{ session('success') }}</div>@endif
    <div class="grid lg:grid-cols-3 gap-5 lg:gap-7.5"><div class="kt-card lg:col-span-2"><div class="kt-card-header"><h3 class="kt-card-title">Detalle</h3></div><div class="kt-card-table"><table class="kt-table align-middle text-sm"><tr><td class="text-secondary-foreground">Cliente</td><td class="text-right"><a class="kt-link" href="{{ route('admin.clients.show', $order->tenant) }}">{{ $order->tenant->name }}</a></td></tr><tr><td class="text-secondary-foreground">Plan</td><td class="text-right font-medium">{{ $order->plan->name }}</td></tr><tr><td class="text-secondary-foreground">Periodo</td><td class="text-right">{{ $order->billing_period_months }} mes(es)</td></tr><tr><td class="text-secondary-foreground">Método</td><td class="text-right">{{ $order->payment_method ?: 'Pendiente de integración' }}</td></tr><tr><td class="text-secondary-foreground">Fecha límite</td><td class="text-right">{{ $order->payment_due_at->format('d/m/Y H:i') }}</td></tr><tr><td class="text-secondary-foreground">Servicio activo desde</td><td class="text-right">{{ $order->activated_at?->format('d/m/Y H:i') }}</td></tr>@if($order->paid_at)<tr><td class="text-secondary-foreground">Pago confirmado</td><td class="text-right">{{ $order->paid_at->format('d/m/Y H:i') }} por {{ $order->paymentConfirmer?->name }}</td></tr>@endif</table></div></div>
    <div class="kt-card content-start"><div class="kt-card-content p-7.5"><div class="text-sm text-secondary-foreground">Total</div><div class="text-3xl text-mono font-semibold mt-2">{{ $order->currency }} {{ number_format((float) $order->amount, 2) }}</div>@if($order->payment_status === 'pending')<form method="POST" action="{{ route('admin.orders.paid', $order) }}" class="grid gap-3 mt-6">@csrf<input class="kt-input" name="payment_method" placeholder="Método (opcional)"><input class="kt-input" name="payment_reference" placeholder="Referencia (opcional)"><button class="kt-btn kt-btn-success justify-center w-full">Marcar como pagado</button></form><p class="text-xs text-secondary-foreground leading-5 mt-4">Esto solo confirma la boleta. El servicio ya está activo y no se modifica.</p>@else<div class="kt-alert kt-alert-success mt-6">Pago confirmado. El servicio permanece activo.</div>@endif</div></div></div>
</div></main>@include('layouts.partials.admin.footer')</div></div>
@endsection
